//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessControlweb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class dbcompany
    {
        [DisplayName("工號")]
        public string UserId { get; set; }

        [DisplayName("卡號")]
        public string CardFrm { get; set; }

        [DisplayName("部門")]
        public string Department { get; set; }

        [DisplayName("性名")]
        public string Name { get; set; }

        [DisplayName("日期")]
        public string Day { get; set; }

        [DisplayName("權限")]
        public string Ambit { get; set; }
    }
}
